// Inline the WASM module as base64 so the package works in Node, Deno, Bun
// and every bundler without asset configuration.
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("../../", import.meta.url);
const wasm = readFileSync(new URL("zig-out/bindings/javascript/wasm/astroz.wasm", root));
writeFileSync(
  new URL("src/wasm.ts", import.meta.url),
  `// Generated by embed-wasm.ts. Do not edit.\nexport const wasmBase64 = "${wasm.toString("base64")}";\n`,
);
console.log(`embedded astroz.wasm (${wasm.length} bytes)`);
